### ISSUE TITLE
遇到点问题

### ISSUE THREAD

**Issue by lorijlh** [NotFound403/payment-spring-boot-samples#1]
首先感谢作者的分享，就是我这边跑demo的时候报了个错
![微信截图_20210309185352](https://user-images.githubusercontent.com/12453300/110460225-e06ea080-8108-11eb-8ba8-fe863d54d8a1.png)
我的理解是要注入ioc的话需要加@Component  @Service 之类的注解，这边没有加这些注解为什么可以引用的？还有我这里报错了是跟这个有关系，具体是我哪里没设置好吗

**Comment by NotFound403** [comment]
请描述分支版本  主要演示的是 微信支付控制器的相关使用  报错是因为 支付的一些敏感参数没有配置导致Bean初始化失败 你只需要将参数正确配置即可，详情可以去阅读文档配置相关的说明，也可以进qq群同大家交流，实际使用中发现了问题可以到主项目进行issue 也可以提交pr共享您的代码
